/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/side-scroll/sphere-3.glb --output src/scenes/HorizontalScrollScene/Sphere.jsx --keepnames --meta 
*/

import React, { forwardRef, useImperativeHandle, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const sphereNames = [
  'Sphere003', 'Sphere004', 'Sphere005', 'Sphere006', 'Sphere007',
  'Sphere008', 'Sphere009', 'Sphere010', 'Sphere011', 'Sphere012',
  'Sphere013', 'Sphere014', 'Sphere015', 'Sphere016', 'Sphere017'
]

export const Sphere = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/side-scroll/sphere-3.glb')

  // Pivots (The Parents - Rotate only)
  const leftPivot = useRef()
  const rightPivot = useRef()

  // Spheres (The Children - Position/Scale only)
  const leftSphere = useRef()
  const rightSphere = useRef()

  const leftRings = useRef([])
  const rightRings = useRef([])

  useImperativeHandle(ref, () => ({
    // Expose Pivots and Spheres
    leftPivot: leftPivot.current,
    rightPivot: rightPivot.current,
    leftSphere: leftSphere.current,
    rightSphere: rightSphere.current,
    // Keep exposing rings for mouse interaction
    leftRings: leftRings.current,
    rightRings: rightRings.current
  }))

  const Ring = ({ name, index, side }) => {
    const node = nodes[name]
    if (!node) return null

    return (
      <mesh
        key={`${side}-${name}`}
        ref={(el) => (side === 'left' ? leftRings : rightRings).current[index] = el}
        name={`${side}-${name}`}
        geometry={node.geometry}
        material={materials['Material.003']}
        position={node.position}
        userData={{ name, side }}
      />
    )
  }

  return (
    <group {...props} dispose={null}>
      {/* Left System */}
      <group ref={leftPivot} name="LeftPivot" position={[0, 0, 0]}>
        <group ref={leftSphere} name="LeftSphere" position={[-6, 0, 0]}>
          {sphereNames.map((name, i) => <Ring key={`left-${name}`} name={name} index={i} side="left" />)}
        </group>
      </group>

      {/* Right System */}
      <group ref={rightPivot} name="RightPivot" position={[0, 0, 0]} rotation={[0, Math.PI, 0]}>
        <group ref={rightSphere} name="RightSphere" position={[-6, 0, 0]}>
          {sphereNames.map((name, i) => <Ring key={`right-${name}`} name={name} index={i} side="right" />)}
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/side-scroll/sphere-3.glb')
