/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Final/public/side-scroll/SterringWheel.glb --output Final/src/scenes/HorizontalScrollScene/SteeringWheel.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SteeringWheel(props) {
  const { nodes, materials } = useGLTF('/side-scroll/SterringWheel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Leather.geometry} material={materials.Leather} scale={1.403} />
      <mesh geometry={nodes.Metal.geometry} material={materials.Metal} scale={1.403} />
    </group>
  )
}

useGLTF.preload('/side-scroll/SterringWheel.glb')
